// Italian names for the SRD bestiary (334 monsters), keyed by index. Only names
// are translated. Creatures with no Italian equivalent keep their original name
// (loanwords are standard in Italian D&D: Aboleth, Balor, Goblin, Bugbear…).
// Dragons follow "Drago <colore> <età>" / "Cucciolo di drago <colore>";
// lycanthropes "<Animale> mannaro (forma …)"; swarms "Sciame di …".
export const MONSTER_IT: Record<string, string> = {
  aboleth: 'Aboleth',
  acolyte: 'Accolito',
  'adult-black-dragon': 'Drago nero adulto',
  'adult-blue-dragon': 'Drago blu adulto',
  'adult-brass-dragon': "Drago d'ottone adulto",
  'adult-bronze-dragon': 'Drago di bronzo adulto',
  'adult-copper-dragon': 'Drago di rame adulto',
  'adult-gold-dragon': "Drago d'oro adulto",
  'adult-green-dragon': 'Drago verde adulto',
  'adult-red-dragon': 'Drago rosso adulto',
  'adult-silver-dragon': "Drago d'argento adulto",
  'adult-white-dragon': 'Drago bianco adulto',
  'air-elemental': "Elementale dell'aria",
  'ancient-black-dragon': 'Drago nero antico',
  'ancient-blue-dragon': 'Drago blu antico',
  'ancient-brass-dragon': "Drago d'ottone antico",
  'ancient-bronze-dragon': 'Drago di bronzo antico',
  'ancient-copper-dragon': 'Drago di rame antico',
  'ancient-gold-dragon': "Drago d'oro antico",
  'ancient-green-dragon': 'Drago verde antico',
  'ancient-red-dragon': 'Drago rosso antico',
  'ancient-silver-dragon': "Drago d'argento antico",
  'ancient-white-dragon': 'Drago bianco antico',
  androsphinx: 'Androsfinge',
  'animated-armor': 'Armatura animata',
  ankheg: 'Ankheg',
  ape: 'Scimmione',
  archmage: 'Arcimago',
  assassin: 'Assassino',
  'awakened-shrub': 'Arbusto risvegliato',
  'awakened-tree': 'Albero risvegliato',
  'axe-beak': "Becco d'ascia",
  azer: 'Azer',
  baboon: 'Babbuino',
  badger: 'Tasso',
  balor: 'Balor',
  bandit: 'Bandito',
  'bandit-captain': 'Capitano dei banditi',
  'barbed-devil': 'Diavolo spinato',
  basilisk: 'Basilisco',
  bat: 'Pipistrello',
  'bearded-devil': 'Diavolo barbuto',
  behir: 'Behir',
  berserker: 'Berserker',
  'black-bear': 'Orso nero',
  'black-dragon-wyrmling': 'Cucciolo di drago nero',
  'black-pudding': 'Poltiglia nera',
  'blink-dog': 'Cane balenante',
  'blood-hawk': 'Falco insanguinato',
  'blue-dragon-wyrmling': 'Cucciolo di drago blu',
  boar: 'Cinghiale',
  'bone-devil': 'Diavolo osseo',
  'brass-dragon-wyrmling': "Cucciolo di drago d'ottone",
  'bronze-dragon-wyrmling': 'Cucciolo di drago di bronzo',
  'brown-bear': 'Orso bruno',
  bugbear: 'Bugbear',
  bulette: 'Bulette',
  camel: 'Cammello',
  cat: 'Gatto',
  centaur: 'Centauro',
  'chain-devil': 'Diavolo delle catene',
  chimera: 'Chimera',
  chuul: 'Chuul',
  'clay-golem': "Golem d'argilla",
  cloaker: 'Cloaker',
  'cloud-giant': 'Gigante delle nuvole',
  cockatrice: 'Cockatrice',
  commoner: 'Popolano',
  'constrictor-snake': 'Serpente costrittore',
  'copper-dragon-wyrmling': 'Cucciolo di drago di rame',
  couatl: 'Couatl',
  crab: 'Granchio',
  crocodile: 'Coccodrillo',
  'cult-fanatic': 'Fanatico del culto',
  cultist: 'Cultista',
  darkmantle: 'Manto oscuro',
  'death-dog': 'Cane della morte',
  'deep-gnome-svirfneblin': 'Gnomo delle profondità (Svirfneblin)',
  deer: 'Cervo',
  deva: 'Deva',
  'dire-wolf': 'Lupo atroce',
  djinni: 'Djinn',
  doppelganger: 'Doppelganger',
  'draft-horse': 'Cavallo da tiro',
  'dragon-turtle': 'Drago-tartaruga',
  dretch: 'Dretch',
  drider: 'Drider',
  drow: 'Drow',
  druid: 'Druido',
  dryad: 'Driade',
  duergar: 'Duergar',
  'dust-mephit': 'Mefit della polvere',
  eagle: 'Aquila',
  'earth-elemental': 'Elementale della terra',
  efreeti: 'Efreet',
  elephant: 'Elefante',
  elk: 'Alce',
  erinyes: 'Erinni',
  ettercap: 'Ettercap',
  ettin: 'Ettin',
  'fire-elemental': 'Elementale del fuoco',
  'fire-giant': 'Gigante del fuoco',
  'flesh-golem': 'Golem di carne',
  'flying-snake': 'Serpente volante',
  'flying-sword': 'Spada volante',
  frog: 'Rana',
  'frost-giant': 'Gigante del gelo',
  gargoyle: 'Gargolla',
  'gelatinous-cube': 'Cubo gelatinoso',
  ghast: 'Ghast',
  ghost: 'Fantasma',
  ghoul: 'Ghoul',
  'giant-ape': 'Scimmione gigante',
  'giant-badger': 'Tasso gigante',
  'giant-bat': 'Pipistrello gigante',
  'giant-boar': 'Cinghiale gigante',
  'giant-centipede': 'Centopiedi gigante',
  'giant-constrictor-snake': 'Serpente costrittore gigante',
  'giant-crab': 'Granchio gigante',
  'giant-crocodile': 'Coccodrillo gigante',
  'giant-eagle': 'Aquila gigante',
  'giant-elk': 'Alce gigante',
  'giant-fire-beetle': 'Coleottero di fuoco gigante',
  'giant-frog': 'Rana gigante',
  'giant-goat': 'Capra gigante',
  'giant-hyena': 'Iena gigante',
  'giant-lizard': 'Lucertola gigante',
  'giant-octopus': 'Piovra gigante',
  'giant-owl': 'Gufo gigante',
  'giant-poisonous-snake': 'Serpente velenoso gigante',
  'giant-rat': 'Ratto gigante',
  'giant-rat-diseased': 'Ratto gigante (malato)',
  'giant-scorpion': 'Scorpione gigante',
  'giant-sea-horse': 'Cavalluccio marino gigante',
  'giant-shark': 'Squalo gigante',
  'giant-spider': 'Ragno gigante',
  'giant-toad': 'Rospo gigante',
  'giant-vulture': 'Avvoltoio gigante',
  'giant-wasp': 'Vespa gigante',
  'giant-weasel': 'Donnola gigante',
  'giant-wolf-spider': 'Ragno lupo gigante',
  'gibbering-mouther': 'Bocca farfugliante',
  glabrezu: 'Glabrezu',
  gladiator: 'Gladiatore',
  gnoll: 'Gnoll',
  goat: 'Capra',
  goblin: 'Goblin',
  'gold-dragon-wyrmling': "Cucciolo di drago d'oro",
  gorgon: 'Gorgone',
  'gray-ooze': 'Melma grigia',
  'green-dragon-wyrmling': 'Cucciolo di drago verde',
  'green-hag': 'Megera verde',
  grick: 'Grick',
  griffon: 'Grifone',
  grimlock: 'Grimlock',
  guard: 'Guardia',
  'guardian-naga': 'Naga guardiana',
  gynosphinx: 'Ginosfinge',
  'half-red-dragon-veteran': 'Veterano mezzo-drago rosso',
  harpy: 'Arpia',
  hawk: 'Falco',
  'hell-hound': 'Mastino infernale',
  hezrou: 'Hezrou',
  'hill-giant': 'Gigante delle colline',
  hippogriff: 'Ippogrifo',
  hobgoblin: 'Hobgoblin',
  homunculus: 'Homunculus',
  'horned-devil': 'Diavolo cornuto',
  'hunter-shark': 'Squalo cacciatore',
  hydra: 'Idra',
  hyena: 'Iena',
  'ice-devil': 'Diavolo del ghiaccio',
  'ice-mephit': 'Mefit del ghiaccio',
  imp: 'Diavoletto',
  'invisible-stalker': 'Cacciatore invisibile',
  'iron-golem': 'Golem di ferro',
  jackal: 'Sciacallo',
  'killer-whale': 'Orca',
  knight: 'Cavaliere',
  kobold: 'Coboldo',
  kraken: 'Kraken',
  lamia: 'Lamia',
  lemure: 'Lemure',
  lich: 'Lich',
  lion: 'Leone',
  lizard: 'Lucertola',
  lizardfolk: 'Uomo lucertola',
  mage: 'Mago',
  'magma-mephit': 'Mefit del magma',
  magmin: 'Magmin',
  mammoth: 'Mammut',
  manticore: 'Mantìcora',
  marilith: 'Marilith',
  mastiff: 'Mastino',
  medusa: 'Medusa',
  merfolk: 'Tritone',
  merrow: 'Merrow',
  mimic: 'Mimic',
  minotaur: 'Minotauro',
  'minotaur-skeleton': 'Scheletro di minotauro',
  mule: 'Mulo',
  mummy: 'Mummia',
  'mummy-lord': 'Signore delle mummie',
  nalfeshnee: 'Nalfeshnee',
  'night-hag': 'Megera notturna',
  nightmare: "Cavallo dell'incubo",
  noble: 'Nobile',
  'ochre-jelly': 'Gelatina ocra',
  octopus: 'Piovra',
  ogre: 'Ogre',
  'ogre-zombie': 'Zombi ogre',
  oni: 'Oni',
  orc: 'Orco',
  otyugh: 'Otyugh',
  owl: 'Gufo',
  owlbear: 'Guforso',
  panther: 'Pantera',
  pegasus: 'Pegaso',
  'phase-spider': 'Ragno delle fasi',
  'pit-fiend': 'Diavolo delle fosse',
  planetar: 'Planetar',
  plesiosaurus: 'Plesiosauro',
  'poisonous-snake': 'Serpente velenoso',
  'polar-bear': 'Orso polare',
  pony: 'Pony',
  priest: 'Sacerdote',
  pseudodragon: 'Pseudodrago',
  'purple-worm': 'Verme purpureo',
  quasit: 'Quasit',
  quipper: 'Quipper',
  rakshasa: 'Rakshasa',
  rat: 'Ratto',
  raven: 'Corvo',
  'red-dragon-wyrmling': 'Cucciolo di drago rosso',
  'reef-shark': 'Squalo di barriera',
  remorhaz: 'Remorhaz',
  rhinoceros: 'Rinoceronte',
  'riding-horse': 'Cavallo da sella',
  roc: 'Roc',
  roper: 'Roper',
  'rug-of-smothering': 'Tappeto soffocante',
  'rust-monster': 'Mostro della ruggine',
  'saber-toothed-tiger': 'Tigre dai denti a sciabola',
  sahuagin: 'Sahuagin',
  salamander: 'Salamandra',
  satyr: 'Satiro',
  scorpion: 'Scorpione',
  scout: 'Esploratore',
  'sea-hag': 'Megera marina',
  'sea-horse': 'Cavalluccio marino',
  shadow: 'Ombra',
  'shambling-mound': 'Cumulo strisciante',
  'shield-guardian': 'Guardiano dello scudo',
  shrieker: 'Fungo stridulo',
  'silver-dragon-wyrmling': "Cucciolo di drago d'argento",
  skeleton: 'Scheletro',
  solar: 'Solar',
  specter: 'Spettro',
  spider: 'Ragno',
  'spirit-naga': 'Naga spirituale',
  sprite: 'Folletto',
  spy: 'Spia',
  'steam-mephit': 'Mefit del vapore',
  stirge: 'Stirge',
  'stone-giant': 'Gigante di pietra',
  'stone-golem': 'Golem di pietra',
  'storm-giant': 'Gigante delle tempeste',
  'succubus-incubus': 'Succube/Incubo',
  'swarm-of-bats': 'Sciame di pipistrelli',
  'swarm-of-beetles': 'Sciame di coleotteri',
  'swarm-of-centipedes': 'Sciame di centopiedi',
  'swarm-of-insects': 'Sciame di insetti',
  'swarm-of-poisonous-snakes': 'Sciame di serpenti velenosi',
  'swarm-of-quippers': 'Sciame di quipper',
  'swarm-of-rats': 'Sciame di ratti',
  'swarm-of-ravens': 'Sciame di corvi',
  'swarm-of-spiders': 'Sciame di ragni',
  'swarm-of-wasps': 'Sciame di vespe',
  tarrasque: 'Tarrasque',
  thug: 'Delinquente',
  tiger: 'Tigre',
  treant: 'Treant',
  'tribal-warrior': 'Guerriero tribale',
  triceratops: 'Triceratopo',
  troll: 'Troll',
  'tyrannosaurus-rex': 'Tirannosauro Rex',
  unicorn: 'Unicorno',
  'vampire-vampire': 'Vampiro',
  'vampire-bat': 'Vampiro (forma di pipistrello)',
  'vampire-mist': 'Vampiro (forma di nebbia)',
  'vampire-spawn': 'Progenie del vampiro',
  veteran: 'Veterano',
  'violet-fungus': 'Fungo violaceo',
  vrock: 'Vrock',
  vulture: 'Avvoltoio',
  warhorse: 'Destriero da guerra',
  'warhorse-skeleton': 'Scheletro di destriero',
  'water-elemental': "Elementale dell'acqua",
  weasel: 'Donnola',
  'werebear-bear': 'Orso mannaro (forma da orso)',
  'werebear-human': 'Orso mannaro (forma umana)',
  'werebear-hybrid': 'Orso mannaro (forma ibrida)',
  'wereboar-boar': 'Cinghiale mannaro (forma da cinghiale)',
  'wereboar-human': 'Cinghiale mannaro (forma umana)',
  'wereboar-hybrid': 'Cinghiale mannaro (forma ibrida)',
  'wererat-human': 'Ratto mannaro (forma umana)',
  'wererat-hybrid': 'Ratto mannaro (forma ibrida)',
  'wererat-rat': 'Ratto mannaro (forma da ratto)',
  'weretiger-human': 'Tigre mannara (forma umana)',
  'weretiger-hybrid': 'Tigre mannara (forma ibrida)',
  'weretiger-tiger': 'Tigre mannara (forma da tigre)',
  'werewolf-human': 'Lupo mannaro (forma umana)',
  'werewolf-hybrid': 'Lupo mannaro (forma ibrida)',
  'werewolf-wolf': 'Lupo mannaro (forma da lupo)',
  'white-dragon-wyrmling': 'Cucciolo di drago bianco',
  wight: 'Wight',
  'will-o-wisp': 'Fuoco fatuo',
  'winter-wolf': 'Lupo invernale',
  wolf: 'Lupo',
  worg: 'Worg',
  wraith: 'Presenza',
  wyvern: 'Viverna',
  xorn: 'Xorn',
  'young-black-dragon': 'Drago nero giovane',
  'young-blue-dragon': 'Drago blu giovane',
  'young-brass-dragon': "Drago d'ottone giovane",
  'young-bronze-dragon': 'Drago di bronzo giovane',
  'young-copper-dragon': 'Drago di rame giovane',
  'young-gold-dragon': "Drago d'oro giovane",
  'young-green-dragon': 'Drago verde giovane',
  'young-red-dragon': 'Drago rosso giovane',
  'young-silver-dragon': "Drago d'argento giovane",
  'young-white-dragon': 'Drago bianco giovane',
  zombie: 'Zombi',
};

/** Italian monster name for an index, falling back to the given English name. */
export function itMonsterName(index: string, fallback: string): string {
  return MONSTER_IT[index] ?? fallback;
}
