// Italian localization for spells. Names + concise summaries are written fresh
// (not verbatim SRD). Phase 1 covers cantrips + level 1 (the range a starting
// campaign uses); higher levels fall back to the English name/description until
// translated. School/metadata localizers cover everything.

export const SCHOOL_IT: Record<string, string> = {
  Abjuration: 'Abiurazione',
  Conjuration: 'Evocazione',
  Divination: 'Divinazione',
  Enchantment: 'Ammaliamento',
  Evocation: 'Invocazione',
  Illusion: 'Illusione',
  Necromancy: 'Necromanzia',
  Transmutation: 'Trasmutazione',
};

const CASTING_TIME_IT: Record<string, string> = {
  '1 action': '1 azione',
  '1 bonus action': '1 azione bonus',
  '1 reaction': '1 reazione',
  '1 minute': '1 minuto',
  '10 minutes': '10 minuti',
  '1 hour': '1 ora',
  '8 hours': '8 ore',
  '12 hours': '12 ore',
  '24 hours': '24 ore',
};

export function localizeSchool(s: string): string {
  return SCHOOL_IT[s] ?? s;
}

export function localizeCastingTime(s: string): string {
  return CASTING_TIME_IT[s] ?? s;
}

export function localizeRange(s: string): string {
  if (s === 'Self') return 'Personale';
  if (s === 'Touch') return 'Contatto';
  if (s === 'Special') return 'Speciale';
  if (s === 'Sight') return 'A vista';
  if (s === 'Unlimited') return 'Illimitata';
  return s
    .replace(/\bfeet\b/gi, 'ft')
    .replace(/\bfoot\b/gi, 'ft')
    .replace(/\bmiles?\b/gi, 'miglia')
    .replace(/\bSelf\b/g, 'Personale');
}

export function localizeDuration(s: string): string {
  return s
    .replace(/Instantaneous/gi, 'Istantaneo')
    .replace(/Until dispelled/gi, 'Finché non dissolto')
    .replace(/Concentration, up to/gi, 'Concentrazione, fino a')
    .replace(/\bhours?\b/gi, 'ore')
    .replace(/\bminutes?\b/gi, 'minuti')
    .replace(/\bdays?\b/gi, 'giorni')
    .replace(/\brounds?\b/gi, 'round');
}

export interface SpellIt {
  name: string;
  summary: string;
}

// index → { Italian name, concise Italian effect }
export const SPELL_IT: Record<string, SpellIt> = {
  // ── Cantrips ──
  'acid-splash': { name: 'Spruzzo Acido', summary: "Una bolla d'acido colpisce fino a due creature vicine (TS Destrezza dimezza i danni acidi)." },
  'chill-touch': { name: 'Tocco Gelido', summary: 'Una mano spettrale infligge danni necrotici e impedisce al bersaglio di curarsi per un turno.' },
  'dancing-lights': { name: 'Luci Danzanti', summary: 'Crei fino a quattro luci fluttuanti che puoi muovere a piacere (concentrazione).' },
  druidcraft: { name: 'Artificio Druidico', summary: 'Piccoli effetti naturali: prevedi il meteo, fai sbocciare un fiore, accendi o spegni una fiammella.' },
  'eldritch-blast': { name: 'Raggio Occulto', summary: 'Scagli raggi di energia occulta a distanza; ognuno infligge danni da forza (aumentano di numero con il livello).' },
  'fire-bolt': { name: 'Dardo di Fuoco', summary: 'Lanci una fiammata contro un bersaglio: danni da fuoco e può incendiare oggetti.' },
  guidance: { name: 'Guida', summary: 'Tocchi un alleato che aggiunge 1d4 a una prova di caratteristica a scelta (concentrazione).' },
  light: { name: 'Luce', summary: 'Fai brillare un oggetto di luce intensa per 1 ora (TS Destrezza se lanciato contro qualcuno).' },
  'mage-hand': { name: 'Mano Magica', summary: 'Evochi una mano spettrale che manipola oggetti leggeri a distanza.' },
  mending: { name: 'Riparare', summary: 'Ripari uno strappo o una rottura in un oggetto (una catena, una lama spezzata, un otre).' },
  message: { name: 'Messaggio', summary: 'Sussurri un messaggio a distanza a una creatura, che può risponderti a bassa voce.' },
  'minor-illusion': { name: 'Illusione Minore', summary: "Crei un suono o un'immagine statica per ingannare i sensi (prova di Indagare per smascherarla)." },
  'poison-spray': { name: 'Spruzzo Velenoso', summary: 'Sprigioni un getto di gas tossico contro una creatura vicina (TS Costituzione, danni da veleno).' },
  prestidigitation: { name: 'Prestidigitazione', summary: 'Trucchetti magici minori: pulire, sporcare, profumare, accendere una candela, creare un ninnolo.' },
  'produce-flame': { name: 'Produrre Fiamma', summary: 'Una fiamma nella mano illumina e può essere scagliata contro un nemico (danni da fuoco).' },
  'ray-of-frost': { name: 'Raggio di Gelo', summary: 'Un raggio gelido infligge danni da freddo e riduce la velocità del bersaglio.' },
  resistance: { name: 'Resistenza', summary: 'Tocchi un alleato che aggiunge 1d4 a un tiro salvezza a scelta (concentrazione).' },
  'sacred-flame': { name: 'Fiamma Sacra', summary: 'Fiamma radiosa piove sul bersaglio ignorando la copertura (TS Destrezza, danni radiosi).' },
  shillelagh: { name: 'Shillelagh', summary: 'Il tuo bastone o randello diventa magico: usi la Saggezza per colpire e infligge 1d8.' },
  'shocking-grasp': { name: 'Tocco Folgorante', summary: 'Una scarica elettrica al contatto: danni da fulmine e il bersaglio non può reagire.' },
  'spare-the-dying': { name: 'Risparmiare i Morenti', summary: 'Stabilizzi con un tocco una creatura morente (a 0 PF).' },
  thaumaturgy: { name: 'Taumaturgia', summary: 'Manifesti un segno di potere divino: voce tonante, fiamme tremolanti, porte che sbattono.' },
  'true-strike': { name: 'Colpo Sicuro', summary: 'Punti un bersaglio: al tuo prossimo turno hai vantaggio al primo attacco contro di esso (concentrazione).' },
  'vicious-mockery': { name: 'Derisione Crudele', summary: 'Insulti magici feriscono la mente: danni psichici e svantaggio al prossimo attacco (TS Saggezza).' },

  // ── Level 1 ──
  alarm: { name: 'Allarme', summary: "Poni un allarme (mentale o udibile) su un'area: ti avverte se una creatura vi entra." },
  'animal-friendship': { name: 'Amicizia con gli Animali', summary: 'Convinci una bestia che non intendi farle del male (TS Saggezza).' },
  bane: { name: 'Rovina', summary: 'Fino a tre nemici sottraggono 1d4 ai tiri per colpire e ai tiri salvezza (TS Carisma, concentrazione).' },
  bless: { name: 'Benedizione', summary: 'Fino a tre alleati aggiungono 1d4 ai tiri per colpire e ai tiri salvezza (concentrazione).' },
  'burning-hands': { name: 'Mani Brucianti', summary: 'Un ventaglio di fiamme investe l’area davanti a te (TS Destrezza, danni da fuoco).' },
  'charm-person': { name: 'Ammaliare Persone', summary: 'Ammalii un umanoide che ti considera un conoscente amichevole (TS Saggezza).' },
  'color-spray': { name: 'Spruzzo di Colori', summary: 'Un lampo di colori acceca le creature vicine per un breve istante.' },
  command: { name: 'Comando', summary: 'Imponi un ordine di una parola a una creatura, che deve obbedire (TS Saggezza).' },
  'comprehend-languages': { name: 'Comprensione dei Linguaggi', summary: 'Comprendi qualsiasi lingua parlata o scritta che senti o tocchi.' },
  'create-or-destroy-water': { name: 'Creare o Distruggere Acqua', summary: 'Crei o distruggi fino a 40 litri d’acqua, o la fai piovere/evaporare.' },
  'cure-wounds': { name: 'Cura Ferite', summary: 'Con un tocco curi 1d8 + mod. da incantatore (non funziona sui non morti).' },
  'detect-evil-and-good': { name: 'Individuazione del Bene e del Male', summary: 'Percepisci celestiali, immondi, non morti e simili nelle vicinanze (concentrazione).' },
  'detect-magic': { name: 'Individuazione del Magico', summary: 'Percepisci la magia entro breve distanza e ne individui la scuola (concentrazione).' },
  'detect-poison-and-disease': { name: 'Individuazione di Veleni e Malattie', summary: 'Individui veleni, creature velenose e malattie nelle vicinanze (concentrazione).' },
  'disguise-self': { name: 'Camuffare Se Stessi', summary: 'Alteri in modo illusorio il tuo aspetto: volto, vestiti, corporatura.' },
  'divine-favor': { name: 'Favore Divino', summary: 'La tua arma emana luce divina: +1d4 danni radiosi ai tuoi colpi (concentrazione).' },
  entangle: { name: 'Intralciare', summary: 'Piante afferrano l’area e trattengono le creature al suolo (TS Forza).' },
  'expeditious-retreat': { name: 'Ritirata Precipitosa', summary: 'Puoi Scattare come azione bonus a ogni turno (concentrazione).' },
  'faerie-fire': { name: 'Fuoco Fatato', summary: 'Avvolgi le creature di luce: gli attacchi contro di esse hanno vantaggio (TS Destrezza, concentrazione).' },
  'false-life': { name: 'Falsa Vita', summary: 'Ottieni 1d4+4 punti ferita temporanei.' },
  'feather-fall': { name: 'Caduta Piumata', summary: 'Fino a cinque creature in caduta scendono lentamente e non subiscono danni (reazione).' },
  'find-familiar': { name: 'Trova Famiglio', summary: 'Evochi uno spirito che assume la forma di un piccolo animale famiglio.' },
  'floating-disk': { name: 'Disco Fluttuante', summary: 'Crei un disco di forza che ti segue e trasporta carichi.' },
  'fog-cloud': { name: 'Nube di Nebbia', summary: 'Crei una nebbia che oscura completamente la vista nell’area (concentrazione).' },
  goodberry: { name: 'Bacche Nutrienti', summary: 'Crei bacche curative: ciascuna nutre e ripristina 1 PF.' },
  grease: { name: 'Grasso', summary: 'Ricopri il pavimento di grasso scivoloso: chi vi entra rischia di cadere (TS Destrezza).' },
  'guiding-bolt': { name: 'Dardo Guida', summary: 'Un lampo radioso colpisce il bersaglio e il prossimo attacco contro di esso ha vantaggio.' },
  'healing-word': { name: 'Parola Guaritrice', summary: 'Come azione bonus, a distanza, curi 1d4 + mod. da incantatore.' },
  'hellish-rebuke': { name: 'Rappresaglia Infernale', summary: 'Come reazione a chi ti ferisce, lo avvolgi di fiamme infernali (TS Destrezza, danni da fuoco).' },
  heroism: { name: 'Eroismo', summary: 'Un alleato diventa immune alla paura e ottiene PF temporanei ogni turno (concentrazione).' },
  'hideous-laughter': { name: 'Risata Isterica', summary: 'Una creatura crolla in una risata incontrollabile, prona e incapace (TS Saggezza, concentrazione).' },
  'hunters-mark': { name: 'Marchio del Cacciatore', summary: 'Marchi una preda: +1d6 danni ai tuoi attacchi contro di essa e vantaggio per seguirla (concentrazione).' },
  identify: { name: 'Identificare', summary: 'Scopri le proprietà magiche di un oggetto e gli incantesimi che lo influenzano.' },
  'illusory-script': { name: 'Scrittura Illusoria', summary: 'Scrivi un messaggio leggibile solo da chi scegli; gli altri vedono un testo innocuo.' },
  'inflict-wounds': { name: 'Infliggere Ferite', summary: 'Un tocco carico di energia negativa infligge 3d10 danni necrotici.' },
  jump: { name: 'Saltare', summary: 'La distanza di salto di una creatura triplica.' },
  longstrider: { name: 'Passo Lungo', summary: 'La velocità di una creatura aumenta di 3 metri per 1 ora.' },
  'mage-armor': { name: 'Armatura Magica', summary: 'Avvolgi una creatura senza armatura di forza protettiva: CA 13 + mod. Destrezza.' },
  'magic-missile': { name: 'Dardo Incantato', summary: 'Tre dardi di forza colpiscono automaticamente i bersagli (1d4+1 ciascuno).' },
  'protection-from-evil-and-good': { name: 'Protezione dal Bene e dal Male', summary: 'Proteggi una creatura da certi tipi di mostri: la attaccano con svantaggio e non possono affascinarla (concentrazione).' },
  'purify-food-and-drink': { name: 'Purificare Cibo e Bevande', summary: 'Purifichi cibo e bevande nell’area da veleni e impurità.' },
  sanctuary: { name: 'Santuario', summary: 'Chi vuole attaccare la creatura protetta deve superare un TS Saggezza o cambiare bersaglio.' },
  shield: { name: 'Scudo', summary: 'Come reazione, +5 alla CA fino al prossimo turno e nessun danno da Dardo Incantato.' },
  'shield-of-faith': { name: 'Scudo della Fede', summary: 'Un campo di forza dona +2 alla CA a una creatura (concentrazione).' },
  'silent-image': { name: 'Immagine Silenziosa', summary: 'Crei l’immagine illusoria di un oggetto o creatura, che puoi muovere (concentrazione).' },
  sleep: { name: 'Sonno', summary: 'Fai addormentare creature per un totale di 5d8 PF, dalle più deboli in su.' },
  'speak-with-animals': { name: 'Parlare con gli Animali', summary: 'Puoi comprendere e parlare con le bestie per 10 minuti.' },
  thunderwave: { name: 'Onda Tonante', summary: 'Un’onda di tuono respinge e ferisce le creature intorno a te (TS Costituzione, danni da tuono).' },
  'unseen-servant': { name: 'Servitore Invisibile', summary: 'Evochi un servitore invisibile che svolge compiti semplici ai tuoi ordini.' },

  // ── Level 2 ──
  'acid-arrow': { name: 'Freccia Acida', summary: 'Una freccia verde colpisce il bersaglio: danni acidi subito e altri alla fine del suo turno successivo.' },
  aid: { name: 'Aiuto', summary: 'Fino a tre creature ottengono +5 PF massimi e attuali per 8 ore.' },
  'alter-self': { name: 'Modellare Se Stessi', summary: 'Ti trasformi: respiro acquatico, armi naturali o un aspetto diverso (concentrazione).' },
  'animal-messenger': { name: 'Messaggero Animale', summary: 'Invii un piccolo animale a recapitare un messaggio a una destinazione che descrivi.' },
  'arcane-lock': { name: 'Blocco Arcano', summary: 'Sigilli magicamente una porta o un baule: solo tu (o chi indichi) puoi aprirli senza forzarli.' },
  'arcanists-magic-aura': { name: 'Aura Magica dell’Arcanista', summary: 'Maschera l’aura magica di una creatura o di un oggetto per ingannare la divinazione.' },
  augury: { name: 'Presagio', summary: 'Chiedi ai poteri superiori se un’azione entro 30 minuti porterà bene, male, entrambi o nulla.' },
  barkskin: { name: 'Pelle Coriacea', summary: 'La pelle del bersaglio si irrobustisce: la sua CA non può scendere sotto 16 (concentrazione).' },
  'blindness-deafness': { name: 'Cecità/Sordità', summary: 'Rendi una creatura cieca o sorda (TS Costituzione).' },
  blur: { name: 'Sfocatura', summary: 'La tua figura si offusca: gli attacchi contro di te hanno svantaggio (concentrazione).' },
  'branding-smite': { name: 'Colpo Marchiante', summary: 'Il prossimo colpo infligge danni radiosi extra e rende il bersaglio luminoso e visibile (concentrazione).' },
  'calm-emotions': { name: 'Calmare Emozioni', summary: 'Plachi le emozioni nell’area, sopprimendo paura o ostilità (TS Carisma, concentrazione).' },
  'continual-flame': { name: 'Fiamma Continua', summary: 'Crei una fiamma perenne e senza calore su un oggetto, come una torcia eterna.' },
  darkness: { name: 'Oscurità', summary: 'Riempi un’area di tenebre magiche che nemmeno la scurovisione penetra (concentrazione).' },
  darkvision: { name: 'Scurovisione', summary: 'Doni a una creatura la capacità di vedere al buio fino a 18 metri per 8 ore.' },
  'detect-thoughts': { name: 'Individuazione dei Pensieri', summary: 'Leggi i pensieri superficiali delle creature vicine e puoi sondarne la mente (concentrazione).' },
  'enhance-ability': { name: 'Potenziare Caratteristica', summary: 'Doni vantaggio alle prove di una caratteristica (e altri benefici) per 1 ora (concentrazione).' },
  'enlarge-reduce': { name: 'Ingrandire/Ridurre', summary: 'Raddoppi o dimezzi le dimensioni di una creatura o oggetto, con effetti su danni e Forza (concentrazione).' },
  enthrall: { name: 'Soggiogare', summary: 'Un flusso di parole distrae le creature: svantaggio a percepire chiunque altro (TS Saggezza).' },
  'find-steed': { name: 'Trova Destriero', summary: 'Evochi uno spirito che assume la forma di un cavallo (o simile) fedele come cavalcatura.' },
  'find-traps': { name: 'Trova Trappole', summary: 'Percepisci la presenza di trappole entro portata (non la loro posizione esatta).' },
  'flame-blade': { name: 'Lama di Fuoco', summary: 'Evochi una spada di fuoco che impugni e con cui attacchi (concentrazione).' },
  'flaming-sphere': { name: 'Sfera Infuocata', summary: 'Crei una sfera di fuoco che muovi per incendiare e travolgere i nemici (TS Destrezza, concentrazione).' },
  'gentle-repose': { name: 'Riposo Tranquillo', summary: 'Preservi un cadavere dalla decomposizione e dal diventare non morto.' },
  'gust-of-wind': { name: 'Raffica di Vento', summary: 'Una linea di vento respinge le creature e disperde gas e vapori (concentrazione).' },
  'heat-metal': { name: 'Arroventare il Metallo', summary: 'Rendi rovente un oggetto di metallo: chi lo tocca subisce danni da fuoco e può lasciarlo cadere (concentrazione).' },
  'hold-person': { name: 'Blocca Persone', summary: 'Paralizzi un umanoide finché non supera un TS Saggezza (concentrazione).' },
  invisibility: { name: 'Invisibilità', summary: 'Una creatura diventa invisibile finché non attacca o lancia un incantesimo (concentrazione).' },
  knock: { name: 'Bussare', summary: 'Apri con un tonfo una serratura, un chiavistello o una porta sbarrata.' },
  'lesser-restoration': { name: 'Ristorare Inferiore', summary: 'Curi una creatura da una malattia o da una condizione (cieca, sorda, paralizzata o avvelenata).' },
  levitate: { name: 'Levitazione', summary: 'Sollevi in verticale una creatura o un oggetto, che fluttua nell’aria (concentrazione).' },
  'locate-animals-or-plants': { name: 'Localizzare Animali o Piante', summary: 'Individui la creatura o pianta di un tipo scelto più vicina entro alcuni chilometri.' },
  'locate-object': { name: 'Localizzare Oggetti', summary: 'Percepisci la direzione di un oggetto noto entro 300 metri (concentrazione).' },
  'magic-mouth': { name: 'Bocca Magica', summary: 'Incanti un oggetto perché pronunci un messaggio quando si verifica una condizione.' },
  'magic-weapon': { name: 'Arma Magica', summary: 'Un’arma non magica diventa +1 al colpire e ai danni (concentrazione).' },
  'mirror-image': { name: 'Immagini Speculari', summary: 'Crei tre duplicati illusori che ingannano gli attacchi diretti a te.' },
  'misty-step': { name: 'Passo Velato', summary: 'Come azione bonus, ti teletrasporti fino a 9 metri in uno spazio che vedi.' },
  moonbeam: { name: 'Raggio di Luna', summary: 'Un raggio di luce argentea incenerisce chi vi si trova (TS Costituzione, concentrazione).' },
  'pass-without-trace': { name: 'Passo senza Tracce', summary: 'Tu e gli alleati vicini ottenete +10 a Furtività e non lasciate tracce (concentrazione).' },
  'prayer-of-healing': { name: 'Preghiera di Guarigione', summary: 'Fino a sei creature recuperano 2d8 + mod. PF (richiede 10 minuti).' },
  'protection-from-poison': { name: 'Protezione dai Veleni', summary: 'Neutralizzi un veleno e dai vantaggio ai TS e resistenza ai danni da veleno.' },
  'ray-of-enfeeblement': { name: 'Raggio di Indebolimento', summary: 'Un raggio nero dimezza i danni degli attacchi in mischia con Forza del bersaglio (concentrazione).' },
  'rope-trick': { name: 'Trucco della Corda', summary: 'Una corda si erge in aria conducendo a uno spazio extradimensionale nascosto.' },
  'scorching-ray': { name: 'Raggi Roventi', summary: 'Scagli tre raggi di fuoco contro uno o più bersagli (attacco a distanza).' },
  'see-invisibility': { name: 'Vedere Invisibilità', summary: 'Vedi le creature e gli oggetti invisibili e scorgi nel Piano Etereo per 1 ora.' },
  shatter: { name: 'Frantumare', summary: 'Un’esplosione di suono assordante danneggia le creature nell’area (TS Costituzione, danni da tuono).' },
  silence: { name: 'Silenzio', summary: 'Crei una sfera di silenzio totale: nessun suono, né incantesimi verbali (concentrazione).' },
  'spider-climb': { name: 'Passo del Ragno', summary: 'Una creatura può camminare su pareti e soffitti a mani libere (concentrazione).' },
  'spike-growth': { name: 'Crescita di Spine', summary: 'Il terreno si riempie di spine: rallenta e ferisce chi lo attraversa (concentrazione).' },
  'spiritual-weapon': { name: 'Arma Spirituale', summary: 'Evochi un’arma spettrale che attacca a distanza come azione bonus (danni da forza).' },
  suggestion: { name: 'Suggestione', summary: 'Convinci una creatura a seguire un’azione ragionevole che proponi (TS Saggezza, concentrazione).' },
  'warding-bond': { name: 'Legame di Protezione', summary: 'Un alleato ottiene +1 CA e ai TS e resistenza ai danni, ma tu subisci metà dei suoi danni (concentrazione).' },
  web: { name: 'Ragnatela', summary: 'Riempi l’area di ragnatele appiccicose che intrappolano le creature (TS Destrezza, concentrazione).' },
  'zone-of-truth': { name: 'Zona di Verità', summary: 'Nell’area le creature non possono mentire deliberatamente (TS Carisma).' },

  // ── Level 3 ──
  'animate-dead': { name: 'Animare Morti', summary: 'Trasformi ossa o cadaveri in scheletri o zombie sotto il tuo controllo.' },
  'beacon-of-hope': { name: 'Faro di Speranza', summary: 'Gli alleati hanno vantaggio ai TS Saggezza e contro morte e recuperano il massimo dalle cure (concentrazione).' },
  'bestow-curse': { name: 'Infliggere Maledizione', summary: 'Maledici una creatura con uno svantaggio a tua scelta (TS Saggezza, concentrazione).' },
  blink: { name: 'Intermittenza', summary: 'Alla fine di ogni tuo turno hai una possibilità di sparire nel Piano Etereo e riapparire.' },
  'call-lightning': { name: 'Chiamare il Fulmine', summary: 'Evochi una nube tempestosa e scagli fulmini ogni turno (TS Destrezza, concentrazione).' },
  clairvoyance: { name: 'Chiaroveggenza', summary: 'Crei un sensore invisibile in un luogo noto per vedere o sentire a distanza (concentrazione).' },
  'conjure-animals': { name: 'Evocare Animali', summary: 'Evochi bestie fatate che combattono al tuo fianco (concentrazione).' },
  counterspell: { name: 'Controincantesimo', summary: 'Come reazione, interrompi l’incantesimo di una creatura mentre lo lancia.' },
  'create-food-and-water': { name: 'Creare Cibo e Acqua', summary: 'Crei cibo e acqua a sufficienza per nutrire diverse persone per un giorno.' },
  daylight: { name: 'Luce del Giorno', summary: 'Crei una sfera di luce solare che dissolve le tenebre magiche più deboli.' },
  'dispel-magic': { name: 'Dissolvi Magie', summary: 'Poni fine agli effetti magici su una creatura, un oggetto o un’area.' },
  fear: { name: 'Paura', summary: 'Un’illusione terrificante fa fuggire i nemici nel cono, che lasciano cadere ciò che impugnano (TS Saggezza, concentrazione).' },
  fireball: { name: 'Palla di Fuoco', summary: 'Una sfera infuocata esplode a distanza investendo l’area (TS Destrezza, 8d6 danni da fuoco).' },
  fly: { name: 'Volare', summary: 'Doni a una creatura una velocità di volo di 18 metri (concentrazione).' },
  'gaseous-form': { name: 'Forma Gassosa', summary: 'Trasformi una creatura in una nebbia che fluttua e passa da piccoli spiragli (concentrazione).' },
  'glyph-of-warding': { name: 'Glifo di Protezione', summary: 'Incidi un glifo che scatena un’esplosione o un incantesimo quando qualcuno ne viola le condizioni.' },
  haste: { name: 'Velocità', summary: 'Un alleato raddoppia la velocità, ottiene +2 CA, vantaggio ai TS Destrezza e un’azione extra (concentrazione).' },
  'hypnotic-pattern': { name: 'Schema Ipnotico', summary: 'Un motivo di luci ammalia e rende inerti le creature nell’area (TS Saggezza, concentrazione).' },
  'lightning-bolt': { name: 'Fulmine', summary: 'Una saetta in linea retta folgora tutto ciò che attraversa (TS Destrezza, danni da fulmine).' },
  'magic-circle': { name: 'Cerchio Magico', summary: 'Un cilindro protegge da (o intrappola) celestiali, immondi, non morti e simili.' },
  'major-image': { name: 'Immagine Superiore', summary: 'Crei un’illusione realistica con suoni, odori e temperatura, che puoi muovere (concentrazione).' },
  'mass-healing-word': { name: 'Parola Guaritrice di Massa', summary: 'Come azione bonus, fino a sei creature recuperano 1d4 + mod. PF.' },
  'meld-into-stone': { name: 'Fondersi con la Pietra', summary: 'Ti fondi con una superficie di pietra abbastanza grande da contenerti.' },
  nondetection: { name: 'Nascondere alla Divinazione', summary: 'Proteggi una creatura, un luogo o un oggetto dalla divinazione magica per 8 ore.' },
  'phantom-steed': { name: 'Destriero Fantasma', summary: 'Evochi un cavallo spettrale che viaggia veloce e instancabile per 1 ora.' },
  'plant-growth': { name: 'Crescita Vegetale', summary: 'Fai crescere la vegetazione rendendo l’area terreno difficile, oppure arricchisci un raccolto.' },
  'protection-from-energy': { name: 'Protezione dall’Energia', summary: 'Doni resistenza a un tipo di danno (acido, freddo, fuoco, fulmine o veleno) per 1 ora (concentrazione).' },
  'remove-curse': { name: 'Rimuovere Maledizione', summary: 'Poni fine a tutte le maledizioni su una creatura o un oggetto che tocchi.' },
  revivify: { name: 'Rivivificare', summary: 'Riporti in vita una creatura morta da meno di un minuto, con 1 PF (serve un diamante).' },
  sending: { name: 'Messaggio a Distanza', summary: 'Invii un breve messaggio a una creatura che conosci, ovunque si trovi, e ricevi risposta.' },
  'sleet-storm': { name: 'Tempesta di Nevischio', summary: 'Ghiaccio e nevischio oscurano la vista, rendono il terreno scivoloso e spezzano la concentrazione (concentrazione).' },
  slow: { name: 'Rallentare', summary: 'Fino a sei creature dimezzano velocità e CA e agiscono più lentamente (TS Saggezza, concentrazione).' },
  'speak-with-dead': { name: 'Parlare con i Morti', summary: 'Poni fino a cinque domande a un cadavere, che risponde brevemente.' },
  'speak-with-plants': { name: 'Parlare con le Piante', summary: 'Comunichi con la vegetazione e puoi chiederle di muoversi o riferire ciò che ha percepito.' },
  'spirit-guardians': { name: 'Spiriti Guardiani', summary: 'Spiriti volteggiano intorno a te ferendo e rallentando i nemici vicini (TS Saggezza, concentrazione).' },
  'stinking-cloud': { name: 'Nube Nauseante', summary: 'Un gas nauseabondo fa perdere il turno alle creature nell’area (TS Costituzione, concentrazione).' },
  'tiny-hut': { name: 'Capanna Minuscola', summary: 'Crei una cupola di forza che ripara fino a nove creature per 8 ore.' },
  tongues: { name: 'Lingue', summary: 'Una creatura comprende qualsiasi lingua parlata e viene compresa da chi la ascolta.' },
  'vampiric-touch': { name: 'Tocco Vampirico', summary: 'Un tocco necrotico ferisce il bersaglio e ti cura di metà dei danni inflitti (concentrazione).' },
  'water-breathing': { name: 'Respirare sott’Acqua', summary: 'Fino a dieci creature possono respirare sott’acqua per 24 ore.' },
  'water-walk': { name: 'Camminare sull’Acqua', summary: 'Fino a dieci creature possono camminare su superfici liquide come fosse terra solida.' },
  'wind-wall': { name: 'Muro di Vento', summary: 'Un muro di vento forte devia proiettili, gas e piccole creature (concentrazione).' },

  // ── Level 4 ──
  'arcane-eye': { name: 'Occhio Arcano', summary: 'Crei un occhio invisibile e fluttuante con cui esplori a distanza, anche in spazi angusti (concentrazione).' },
  banishment: { name: 'Bandire', summary: 'Esili una creatura in un altro piano finché mantieni la concentrazione (TS Carisma).' },
  'black-tentacles': { name: 'Tentacoli Neri', summary: 'Tentacoli emergono dal suolo, afferrano e danneggiano le creature nell’area (TS Destrezza, concentrazione).' },
  blight: { name: 'Avvizzimento', summary: 'Prosciughi la forza vitale di una creatura o pianta (TS Costituzione, danni necrotici).' },
  compulsion: { name: 'Coazione', summary: 'Costringi le creature nell’area a muoversi nella direzione che indichi (TS Saggezza, concentrazione).' },
  confusion: { name: 'Confusione', summary: 'Le creature nell’area agiscono in modo casuale e incontrollato (TS Saggezza, concentrazione).' },
  'conjure-minor-elementals': { name: 'Evocare Elementali Minori', summary: 'Evochi alcuni elementali che combattono ai tuoi ordini (concentrazione).' },
  'conjure-woodland-beings': { name: 'Evocare Creature Silvane', summary: 'Evochi folletti e creature fatate che combattono per te (concentrazione).' },
  'control-water': { name: 'Controllare l’Acqua', summary: 'Comandi grandi masse d’acqua: onde, correnti, allontanamento o inondazioni (concentrazione).' },
  'death-ward': { name: 'Barriera contro la Morte', summary: 'La prima volta che scenderesti a 0 PF resti invece a 1 PF (8 ore).' },
  'dimension-door': { name: 'Porta Dimensionale', summary: 'Ti teletrasporti (con un compagno) fino a 150 metri in un luogo che immagini.' },
  divination: { name: 'Divinazione', summary: 'Poni una domanda sugli eventi entro una settimana e ottieni un presagio veritiero.' },
  'dominate-beast': { name: 'Dominare Bestie', summary: 'Controlli mentalmente una bestia (TS Saggezza, concentrazione).' },
  fabricate: { name: 'Fabbricare', summary: 'Trasformi materie prime in un oggetto finito su vasta scala.' },
  'faithful-hound': { name: 'Segugio Fedele', summary: 'Evochi un mastino invisibile che fa la guardia e attacca chi si avvicina di soppiatto.' },
  'fire-shield': { name: 'Scudo di Fuoco', summary: 'Fiamme ti avvolgono: resistenza al freddo o al fuoco e danni a chi ti colpisce in mischia.' },
  'freedom-of-movement': { name: 'Libertà di Movimento', summary: 'Una creatura ignora il terreno difficile e non può essere trattenuta o paralizzata magicamente (1 ora).' },
  'giant-insect': { name: 'Insetto Gigante', summary: 'Ingrandisci insetti comuni trasformandoli in bestie giganti al tuo comando (concentrazione).' },
  'greater-invisibility': { name: 'Invisibilità Superiore', summary: 'Una creatura resta invisibile anche mentre attacca o lancia incantesimi (concentrazione).' },
  'guardian-of-faith': { name: 'Guardiano della Fede', summary: 'Evochi un guardiano spettrale che ferisce chi gli si avvicina con intenti ostili.' },
  'hallucinatory-terrain': { name: 'Terreno Illusorio', summary: 'Fai apparire un vasto tratto di terreno come un ambiente naturale diverso.' },
  'ice-storm': { name: 'Tempesta di Ghiaccio', summary: 'Grandine rovinosa martella l’area (TS Destrezza, danni contundenti e da freddo).' },
  'locate-creature': { name: 'Localizzare Creature', summary: 'Percepisci la direzione di una creatura o di un tipo di creatura noto (concentrazione).' },
  'phantasmal-killer': { name: 'Assassino Fantasma', summary: 'Un’immagine terrificante perseguita una creatura infliggendole danni psichici (TS Saggezza, concentrazione).' },
  polymorph: { name: 'Metamorfosi', summary: 'Trasformi una creatura in una bestia di grado di sfida pari o inferiore (TS Saggezza, concentrazione).' },
  'private-sanctum': { name: 'Rifugio Privato', summary: 'Rendi un’area sicura da spie, teletrasporti e divinazione.' },
  'resilient-sphere': { name: 'Sfera Resiliente', summary: 'Racchiudi una creatura o un oggetto in una sfera di forza impenetrabile (concentrazione).' },
  'secret-chest': { name: 'Baule Segreto', summary: 'Nascondi un baule nel Piano Etereo, richiamandolo quando vuoi.' },
  'stone-shape': { name: 'Modellare la Pietra', summary: 'Plasmi la pietra come argilla, creando forme e aperture.' },
  stoneskin: { name: 'Pelle di Pietra', summary: 'Una creatura ottiene resistenza ai danni fisici non magici (concentrazione).' },
  'wall-of-fire': { name: 'Muro di Fuoco', summary: 'Erigi un muro fiammeggiante che brucia chi vi passa attraverso o gli sta accanto (concentrazione).' },

  // ── Level 5 ──
  'animate-objects': { name: 'Animare Oggetti', summary: 'Dai vita a oggetti inanimati che combattono ai tuoi ordini (concentrazione).' },
  'antilife-shell': { name: 'Guscio Antivita', summary: 'Una barriera ti circonda impedendo l’avvicinamento delle creature viventi (concentrazione).' },
  'arcane-hand': { name: 'Mano Arcana', summary: 'Evochi una gigantesca mano di forza che colpisce, spinge, afferra o protegge (concentrazione).' },
  awaken: { name: 'Risvegliare', summary: 'Doni intelletto e parola a una bestia o pianta, che diventa tua amica.' },
  cloudkill: { name: 'Nube di Morte', summary: 'Una nube di gas velenoso avanza e uccide (TS Costituzione, concentrazione).' },
  commune: { name: 'Comunione', summary: 'Poni fino a tre domande sì/no alla tua divinità.' },
  'commune-with-nature': { name: 'Comunione con la Natura', summary: 'Ottieni conoscenza del territorio circostante: terreno, creature, acque, insediamenti.' },
  'cone-of-cold': { name: 'Cono di Freddo', summary: 'Un’ondata di aria gelida investe l’area davanti a te (TS Costituzione, danni da freddo).' },
  'conjure-elemental': { name: 'Evocare Elementali', summary: 'Evochi un potente elementale che combatte per te (concentrazione).' },
  'contact-other-plane': { name: 'Contattare Altri Piani', summary: 'Interpelli un’entità extraplanare per avere risposte, rischiando la tua mente (TS Intelligenza).' },
  contagion: { name: 'Contagio', summary: 'Il tuo tocco infetta una creatura con una malattia debilitante (TS Costituzione).' },
  creation: { name: 'Creazione', summary: 'Crei un oggetto di materia vegetale o minerale che dura per un tempo limitato.' },
  'dispel-evil-and-good': { name: 'Dissolvere il Bene e il Male', summary: 'Ti proteggi da celestiali, immondi e non morti e puoi scacciarli o bandirli (concentrazione).' },
  'dominate-person': { name: 'Dominare Persone', summary: 'Controlli mentalmente un umanoide (TS Saggezza, concentrazione).' },
  dream: { name: 'Sogno', summary: 'Entri nei sogni di una creatura per comunicare con lei o tormentarla.' },
  'flame-strike': { name: 'Colonna di Fuoco', summary: 'Una colonna di fuoco divino piove dall’alto sull’area (TS Destrezza, danni da fuoco e radiosi).' },
  geas: { name: 'Comando Vincolante', summary: 'Imponi a una creatura un ordine da seguire, pena danni psichici (TS Saggezza).' },
  'greater-restoration': { name: 'Ristorare Superiore', summary: 'Rimuovi un male grave: maledizione, pietrificazione, riduzione di caratteristica o di PF massimi.' },
  hallow: { name: 'Consacrare', summary: 'Consacri un’area con effetti protettivi persistenti contro certi tipi di creature.' },
  'hold-monster': { name: 'Blocca Mostri', summary: 'Paralizzi una creatura qualsiasi finché non supera un TS Saggezza (concentrazione).' },
  'insect-plague': { name: 'Flagello di Insetti', summary: 'Uno sciame di insetti pungenti riempie l’area e ferisce chi vi si trova (TS Costituzione, concentrazione).' },
  'legend-lore': { name: 'Sapienza Leggendaria', summary: 'Apprendi informazioni leggendarie su una persona, un luogo o un oggetto famoso.' },
  'mass-cure-wounds': { name: 'Cura Ferite di Massa', summary: 'Fino a sei creature nell’area recuperano 3d8 + mod. PF.' },
  mislead: { name: 'Ingannare', summary: 'Diventi invisibile e crei un tuo doppio illusorio che puoi controllare (concentrazione).' },
  'modify-memory': { name: 'Modificare Ricordi', summary: 'Alteri o cancelli un ricordo recente di una creatura (TS Saggezza, concentrazione).' },
  passwall: { name: 'Passamuro', summary: 'Apri un passaggio temporaneo attraverso legno, pietra o intonaco.' },
  'planar-binding': { name: 'Vincolo Planare', summary: 'Leghi al tuo servizio una creatura extraplanare per 24 ore (TS Carisma).' },
  'raise-dead': { name: 'Rialzare i Morti', summary: 'Riporti in vita una creatura morta da non più di 10 giorni (serve un diamante).' },
  reincarnate: { name: 'Reincarnare', summary: 'Riporti in vita una creatura in un nuovo corpo, di specie forse diversa.' },
  scrying: { name: 'Scrutare', summary: 'Osservi e ascolti a distanza una creatura che scegli (TS Saggezza, concentrazione).' },
  seeming: { name: 'Sembianza', summary: 'Cambi l’aspetto illusorio di diverse creature (TS Carisma).' },
  telekinesis: { name: 'Telecinesi', summary: 'Muovi con la mente creature e oggetti a distanza (concentrazione).' },
  'telepathic-bond': { name: 'Legame Telepatico', summary: 'Crei un legame telepatico tra più creature per 1 ora.' },
  'teleportation-circle': { name: 'Cerchio di Teletrasporto', summary: 'Tracci un cerchio che apre un portale verso un cerchio permanente noto.' },
  'tree-stride': { name: 'Passo Arboreo', summary: 'Entri in un albero ed esci da un altro dello stesso tipo nelle vicinanze (concentrazione).' },
  'wall-of-force': { name: 'Muro di Forza', summary: 'Erigi una barriera invisibile e quasi indistruttibile (concentrazione).' },
  'wall-of-stone': { name: 'Muro di Pietra', summary: 'Crei un muro di pietra solido che puoi modellare (concentrazione).' },

  // ── Level 6 ──
  'blade-barrier': { name: 'Barriera di Lame', summary: 'Erigi un muro di lame vorticanti che feriscono chi lo attraversa (TS Destrezza, concentrazione).' },
  'chain-lightning': { name: 'Fulmine a Catena', summary: 'Un fulmine colpisce un bersaglio e rimbalza su altri vicini (TS Destrezza, danni da fulmine).' },
  'circle-of-death': { name: 'Cerchio di Morte', summary: 'Un’ondata di energia negativa investe l’area (TS Costituzione, danni necrotici).' },
  'conjure-fey': { name: 'Evocare Fata', summary: 'Evochi una potente creatura fatata al tuo servizio (concentrazione).' },
  contingency: { name: 'Contingenza', summary: 'Predisponi un incantesimo che scatta automaticamente a una condizione stabilita.' },
  'create-undead': { name: 'Creare Non Morti', summary: 'Trasformi cadaveri in ghoul (o non morti più potenti) sotto il tuo controllo.' },
  disintegrate: { name: 'Disintegrazione', summary: 'Un raggio verde può ridurre in polvere una creatura o un oggetto (TS Destrezza, danni da forza).' },
  eyebite: { name: 'Malocchio', summary: 'Il tuo sguardo assonna, spaventa o accascia le creature (TS Saggezza, concentrazione).' },
  'find-the-path': { name: 'Trovare il Sentiero', summary: 'Conosci sempre la via più diretta per un luogo che hai visitato (concentrazione).' },
  'flesh-to-stone': { name: 'Carne in Pietra', summary: 'Trasformi lentamente una creatura in statua di pietra (TS Costituzione, concentrazione).' },
  forbiddance: { name: 'Interdizione', summary: 'Proteggi un’area da teletrasporto e da certi tipi di creature, ferendole se entrano.' },
  'freezing-sphere': { name: 'Sfera Congelante', summary: 'Un globo di freddo esplode nell’area e può ghiacciare l’acqua (TS Costituzione, danni da freddo).' },
  'globe-of-invulnerability': { name: 'Globo di Invulnerabilità', summary: 'Una sfera attorno a te blocca gli incantesimi di 5° livello o inferiore lanciati dall’esterno (concentrazione).' },
  'guards-and-wards': { name: 'Guardie e Protezioni', summary: 'Difendi un intero edificio con una rete di effetti magici: nebbia, porte bloccate, confusione.' },
  harm: { name: 'Ferire', summary: 'Infliggi enormi danni necrotici a una creatura e ne riduci i PF massimi (TS Costituzione).' },
  heal: { name: 'Guarire', summary: 'Ripristini 70 PF a una creatura e la curi da cecità, sordità e malattie.' },
  'heroes-feast': { name: 'Banchetto degli Eroi', summary: 'Un banchetto magico cura, immunizza e potenzia chi vi partecipa per 24 ore.' },
  'instant-summons': { name: 'Convocazione Istantanea', summary: 'Richiami a te all’istante un oggetto preparato, ovunque si trovi.' },
  'irresistible-dance': { name: 'Danza Irresistibile', summary: 'Costringi una creatura a danzare goffamente e indifesa (TS Saggezza, concentrazione).' },
  'magic-jar': { name: 'Vaso Magico', summary: 'Trasferisci la tua anima in un contenitore e poi nel corpo di un’altra creatura (TS Carisma).' },
  'mass-suggestion': { name: 'Suggestione di Massa', summary: 'Imponi un’azione ragionevole a molte creature contemporaneamente (TS Saggezza).' },
  'move-earth': { name: 'Spostare la Terra', summary: 'Rimodelli il terreno su vasta scala: colline, trincee, avvallamenti (concentrazione).' },
  'planar-ally': { name: 'Alleato Planare', summary: 'Chiami una creatura extraplanare che contratta il suo aiuto in cambio di un compenso.' },
  'programmed-illusion': { name: 'Illusione Programmata', summary: 'Prepari un’illusione che si attiva a una condizione precisa.' },
  sunbeam: { name: 'Raggio di Sole', summary: 'Un raggio di luce solare acceca e incenerisce i nemici in linea (TS Costituzione, danni radiosi, concentrazione).' },
  'transport-via-plants': { name: 'Trasporto Vegetale', summary: 'Colleghi due grandi piante creando un portale tra di esse.' },
  'true-seeing': { name: 'Vista Autentica', summary: 'Una creatura vede nel buio, scorge l’invisibile e smaschera le illusioni (1 ora).' },
  'wall-of-ice': { name: 'Muro di Ghiaccio', summary: 'Erigi un muro di ghiaccio che blocca e ferisce (TS Destrezza, concentrazione).' },
  'wall-of-thorns': { name: 'Muro di Spine', summary: 'Crei una barriera di rovi che ostacola e lacera chi la attraversa (concentrazione).' },
  'wind-walk': { name: 'Camminata del Vento', summary: 'Tu e i tuoi compagni diventate nubi di vapore che viaggiano rapide in volo.' },
  'word-of-recall': { name: 'Parola del Ritorno', summary: 'Tu e alcuni compagni vi teletrasportate all’istante in un rifugio prestabilito.' },

  // ── Level 7 ──
  'arcane-sword': { name: 'Spada Arcana', summary: 'Evochi una spada di forza spettrale con cui attacchi a distanza ogni turno (concentrazione).' },
  'conjure-celestial': { name: 'Evocare Celestiale', summary: 'Evochi una creatura celestiale al tuo servizio (concentrazione).' },
  'delayed-blast-fireball': { name: 'Palla di Fuoco Ritardata', summary: 'Una sfera di fuoco cresce d’intensità finché non la scateni (TS Destrezza, concentrazione).' },
  'divine-word': { name: 'Verbo Divino', summary: 'Una parola di potere che acceca, assorda, stordisce o uccide i nemici in base ai loro PF (TS Carisma).' },
  etherealness: { name: 'Etereo', summary: 'Entri nel Piano Etereo, attraversando la materia del mondo reale.' },
  'finger-of-death': { name: 'Dito della Morte', summary: 'Energia negativa infligge danni necrotici; se uccide un umanoide, ne fai uno zombie ai tuoi ordini (TS Costituzione).' },
  'fire-storm': { name: 'Tempesta di Fuoco', summary: 'Fiamme divampano in un’area che plasmi a piacere (TS Destrezza, danni da fuoco).' },
  forcecage: { name: 'Gabbia di Forza', summary: 'Imprigioni le creature in una gabbia o scatola di forza inviolabile.' },
  'magnificent-mansion': { name: 'Magione Magnifica', summary: 'Crei una dimora extradimensionale confortevole con servitori invisibili.' },
  'mirage-arcane': { name: 'Miraggio Arcano', summary: 'Trasformi l’aspetto (e in parte la sostanza) di un vasto terreno per un giorno.' },
  'plane-shift': { name: 'Spostamento Planare', summary: 'Ti teletrasporti con dei compagni su un altro piano d’esistenza (TS Carisma per i bersagli ostili).' },
  'prismatic-spray': { name: 'Spruzzo Prismatico', summary: 'Otto raggi colorati investono i nemici, ciascuno con un effetto diverso (TS Destrezza).' },
  'project-image': { name: 'Proiettare Immagine', summary: 'Crei una copia illusoria di te stesso che controlli a grande distanza (concentrazione).' },
  regenerate: { name: 'Rigenerazione', summary: 'Curi una creatura e le fai ricrescere gli arti perduti (PF ripristinati ogni turno per 1 ora).' },
  resurrection: { name: 'Resurrezione', summary: 'Riporti in vita una creatura morta da non più di un secolo (serve un diamante prezioso).' },
  'reverse-gravity': { name: 'Inversione della Gravità', summary: 'In un’area la gravità si inverte e le creature cadono verso l’alto (TS Destrezza, concentrazione).' },
  sequester: { name: 'Sequestrare', summary: 'Nascondi e poni in stasi una creatura o un oggetto, invisibile alla divinazione.' },
  simulacrum: { name: 'Simulacro', summary: 'Crei un duplicato di ghiaccio e neve di una creatura, obbediente ma dimezzato.' },
  symbol: { name: 'Simbolo', summary: 'Incidi un glifo letale che scatena un effetto dannoso quando viene attivato.' },
  teleport: { name: 'Teletrasporto', summary: 'Ti trasporti all’istante a grande distanza, con precisione variabile secondo la familiarità del luogo.' },

  // ── Level 8 ──
  'animal-shapes': { name: 'Forme Animali', summary: 'Trasformi diversi alleati consenzienti in bestie (concentrazione).' },
  'antimagic-field': { name: 'Campo Antimagia', summary: 'Una sfera attorno a te sopprime ogni magia al suo interno (concentrazione).' },
  'antipathy-sympathy': { name: 'Antipatia/Simpatia', summary: 'Rendi un oggetto o un’area repellente o irresistibile per un tipo di creatura (TS Saggezza).' },
  clone: { name: 'Clone', summary: 'Fai crescere un duplicato inerte di una creatura che ne accoglierà l’anima alla morte.' },
  'control-weather': { name: 'Controllare il Clima', summary: 'Modifichi il tempo atmosferico su una vasta area (concentrazione).' },
  demiplane: { name: 'Semipiano', summary: 'Apri una porta verso un piccolo spazio extradimensionale che crei.' },
  'dominate-monster': { name: 'Dominare Mostri', summary: 'Controlli mentalmente qualsiasi creatura (TS Saggezza, concentrazione).' },
  earthquake: { name: 'Terremoto', summary: 'Scateni un sisma che apre crepe, abbatte strutture e atterra le creature (TS Destrezza, concentrazione).' },
  feeblemind: { name: 'Rimbecillire', summary: 'Devasti l’intelletto di una creatura, azzerandone Intelligenza e Carisma (TS Intelligenza, danni psichici).' },
  glibness: { name: 'Parlantina', summary: 'Per 1 ora ogni tua prova di Carisma ottiene almeno 15 e non puoi essere smascherato come bugiardo.' },
  'holy-aura': { name: 'Aura Sacra', summary: 'Gli alleati vicini brillano di luce sacra: vantaggio ai TS e protezione dagli immondi (concentrazione).' },
  'incendiary-cloud': { name: 'Nube Incendiaria', summary: 'Una nube di fumo e braci ardenti si muove e brucia (TS Destrezza, concentrazione).' },
  maze: { name: 'Labirinto', summary: 'Bandisci una creatura in un labirinto extradimensionale finché non trova l’uscita (concentrazione).' },
  'mind-blank': { name: 'Mente Impenetrabile', summary: 'Rendi una creatura immune a lettura del pensiero, ammaliamento e divinazione per 24 ore.' },
  'power-word-stun': { name: 'Parola di Potere: Stordire', summary: 'Una parola stordisce all’istante una creatura con 150 PF o meno.' },
  sunburst: { name: 'Deflagrazione Solare', summary: 'Un lampo di luce solare acceca e incenerisce le creature nell’area (TS Costituzione, danni radiosi).' },

  // ── Level 9 ──
  'astral-projection': { name: 'Proiezione Astrale', summary: 'Proietti te e i compagni nel Piano Astrale, lasciando i corpi in stasi.' },
  foresight: { name: 'Preveggenza', summary: 'Per 8 ore una creatura ha vantaggio a tiri, prove e TS e non può essere colta di sorpresa.' },
  gate: { name: 'Portale', summary: 'Apri un portale verso un altro piano e puoi richiamare una creatura specifica (concentrazione).' },
  imprisonment: { name: 'Prigionia', summary: 'Imprigioni una creatura in una forma di reclusione magica quasi eterna (TS Saggezza).' },
  'mass-heal': { name: 'Guarigione di Massa', summary: 'Distribuisci fino a 700 PF di cura tra le creature scelte, curandone anche i mali.' },
  'meteor-swarm': { name: 'Sciame di Meteore', summary: 'Sfere infuocate precipitano su vaste aree distanti (TS Destrezza, danni da fuoco e contundenti).' },
  'power-word-kill': { name: 'Parola di Potere: Uccidere', summary: 'Una parola uccide all’istante una creatura con 100 PF o meno.' },
  'prismatic-wall': { name: 'Muro Prismatico', summary: 'Erigi un muro di sette strati colorati, ciascuno con un effetto letale diverso.' },
  shapechange: { name: 'Mutare Forma', summary: 'Ti trasformi in un’altra creatura, anche potente, conservando la tua mente (concentrazione).' },
  'storm-of-vengeance': { name: 'Tempesta della Vendetta', summary: 'Evochi una tempesta immane con fulmini, grandine, acido e venti (concentrazione).' },
  'time-stop': { name: 'Fermare il Tempo', summary: 'Il tempo si ferma per tutti tranne te: agisci per alcuni turni indisturbato.' },
  'true-polymorph': { name: 'Metamorfosi Superiore', summary: 'Trasformi una creatura o un oggetto in qualcos’altro, anche in modo permanente (TS Saggezza, concentrazione).' },
  'true-resurrection': { name: 'Resurrezione Autentica', summary: 'Riporti in vita una creatura morta da fino a 200 anni, anche senza corpo.' },
  weird: { name: 'Terrore', summary: 'Materializzi le paure più profonde dei nemici nell’area, che possono morirne (TS Saggezza, concentrazione).' },
  wish: { name: 'Desiderio', summary: 'L’incantesimo più potente: replichi qualsiasi incantesimo o alteri la realtà secondo il tuo desiderio.' },
};
